version: '3.9'

services:
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_DB: wave_translation
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:11.3.1
    command: migrate
    depends_on:
      - db
    volumes:
      - ./sql:/flyway/sql
    environment:
      - FLYWAY_URL=jdbc:postgresql://db:5432/wave_translation
      - FLYWAY_USER=app_user
      - FLYWAY_PASSWORD=secret
      - FLYWAY_LOCATIONS=filesystem:/flyway/sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
